apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-backend
spec:
  selector:
    matchLabels:
      app: internship-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: internship-backend
    spec:
      containers:
        - name: internship1
          image: suyashsamant/internship1:latest
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: postgres

            - name: DB_NAME  # Setting Database name from configMap
              value: postgres

            - name: DB_USERNAME  # Setting Database username from Secret
              value: postgres

            - name: DB_PASSWORD # Setting Database password from Secret
              value: postgres

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: internship-backend
spec:
  selector:
    app: internship-backend
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.