apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-backend-new
spec:
  selector:
    matchLabels:
      app: internship-backend-new
  replicas: 3
  template:
    metadata:
      labels:
        app: internship-backend-new
    spec:
      containers:
        - name: internship-backend-new
          image: suyashsamant/internship-backend-new:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"   # Corrected database host address
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
